unsloth:
  learning_rate: 1.0e-5
  warmup_ratio: 0.03
  weight_decay: 0.0
  # If you bump model to 14B, consider:
  #   - num_generations: 2–4
  #   - max_completion_length: 512–768
  #   - gradient_accumulation_steps: 16–32
logging:
  log_dir: "/opt/azr/runs"
  save_steps: 100
  eval_steps: 1000
